version: 0.0
os: linux
files:
  - source: /AwsCodeDeployTest/bin/Release/netcoreapp2.1/publish/
    destination: /home/codedeploytest/publish/
hooks:
  ApplicationStop:
    - location: cp-scripts/stop.sh
      timeout: 180
  ApplicationStart:
    - location: cp-scripts/start.sh
      timeout: 180
