version: 0.2
 
phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish --configuration Release AwsCodeDeployTest
artifacts:
  files:
    - bin/Release/netcoreapp2.1/publish/*